### PR TITLE
Keep both Fibonacci and FNV_1A hash functions

### PR DESCRIPTION
**Pull request by kstppd**
This replaces #47  with a cleaner implementation.

### CODE REVIEW

**Comment by ursg** [comment]
I guess technically, that sizeof check should be ```sizeof(GID) <= sizeof(uint32_t)```. Because if now you were to plonk in a 
```
struct {
  uint32_t a;
  uint16_t b;
}
```
That would be size 6, would go through the constexpr if and fail because that type can't even be typeconverted to uint32_t.

But maybe I'm just nitpicking here. The code works.

Now let me see how I merge this (because I want the newDelete implementation together with this one).

**Comment by kstppd** [comment]
True let me do a quick push of that first

**Comment by kstppd** [comment]
Ok done

**Comment by ursg** [comment]
This is merged (in a slightly different formulation) in https://github.com/fmihpc/vlasiator/pull/588/commits/17d568b022b69b921bc92d8550662a303eb56549

**Pull request closed without merging**
