### PR TITLE
Skip non existent spatial cells in shrink to fit

### PR DESCRIPTION
**Pull request by kstppd**

### CODE REVIEW

**Comment by ursg** [comment]
Ah, btw, I just noticed that this introduced a new warning in grid.cpp:
```
grid.cpp: In function 'void shrink_to_fit_grid_data(dccrg::Dccrg<spatial_cell::SpatialCell, dccrg::Cartesian_Geometry>&)':
grid.cpp:744:7: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
  744 |       else
      |       ^~~~
grid.cpp:748:10: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  748 |          mpiGrid[remote_cells[i - cells.size()]]->shrink_to_fit();
      |          ^~~~~~~
```
And I suspect this is, indeed, wrong. Wouldn't it cause an out-of-bounds memory access for small i?
At least it's not good style, so we should fix it.

**Comment by kstppd** [comment]
And once again I hate it when people do not use curly braces

**Comment by markusbattarbee** [comment]
umm, there's braces missing from the if-else-construct, and now that the else-bit has several commands, the behaviour changes!

**Comment by kstppd** [comment]
Yeah...

**Comment by kstppd** [comment]
Added the missing braces

**Comment by ursg** [comment]
I re-PR'd this as a proper pull request for dev here: https://github.com/fmihpc/vlasiator/pull/658

**Pull request merged**
