### PR TITLE
More threading of ionosphere solver

### PR DESCRIPTION
**Pull request by ykempf**
Barriers in vlasiator.cpp for reliable timing to be removed, and commented debugging code to be cleaned up before merging.

### CODE REVIEW

**Comment by ykempf** [comment]
So I was attempting to have one large parallel region with the for loops inside, but it looks to me like the reductions are not done right after the for loops. As long as this is not clarified, I am not sure if there's other bugs. The current version runs Magnetosphere_3D_small on 16 tasks x 16 threads (1 Mahti node) and yields
The absolute 0-distance between both datasets is 1.62981e-09
The relative 0-distance between both datasets is 1.62682e-15
on proton/vg_rho after 10 steps, so it seems OK (testpackage).

Also, ionosphere-solve runs in 17.3 s in my reference case, and 6.59 s in this more threaded version.

**Comment by ykempf** [comment]
After 2 s of Magnetosphere_3D_small I get
```
Statistics on file: size 13308 min = 969116 max = 1.03554e+06 average = 1.00007e+06 standard deviation 55.2393
Statistics on file: size 13308 min = 969116 max = 1.03554e+06 average = 1.00007e+06 standard deviation 55.2393
The absolute 0-distance between both datasets is 0.000312453
The relative 0-distance between both datasets is 3.01731e-10
```
The full test is queuing, as the slower base version runs in just a bit longer than the test queue limit on Mahti.

**Comment by ykempf** [comment]
Please have a thorough look whether there is more race conditions like the srqt(sourcenorm) or the one I preempted (I think) with potentialInt (which we aren't running atm).

**Comment by ykempf** [comment]
For the full 3 s we get a speed up from 530 to 185 s. And diffs reach
Statistics on file: size 13308 min = 954898 max = 1.05194e+06 average = 1.00013e+06 standard deviation 82.3212
Statistics on file: size 13308 min = 954898 max = 1.05194e+06 average = 1.00013e+06 standard deviation 82.3212
The absolute 0-distance between both datasets is 0.0162046
The relative 0-distance between both datasets is 1.54045e-08

**Comment by ykempf** [comment]
I ran now Magnetosphere_3D_small for 100 steps/1 s. I look at the relative diff of proton/vg_rho.

base vs improved: 10⁻¹³
improved vs improved rerun (same thread count): 10⁻¹¹
improved vs improved (different thread count): 10⁻¹¹
improved vs improved (yet different count): 10⁻¹³
base vs base rerun (same thread count): 10⁻¹³
base vs base (different thread count): 10⁻¹¹
base vs base (yet different count): 10⁻¹¹

So maybe there is issues with task/thread count changes, but they don't come from this threading effort I think.

**Comment by ursg** [comment]
Yup, I can confirm, this runs nicely and quickly.
The differnces on that order are probably entirely accountable to floating point issues. The solver is iffy as it is already, so any little bit of jitter will probably drive it into disconvergence with the low eigenvalue even faster. Then we restart it slightly earlier, and end up with a slightly different result. Not too satisfying, but at least the results look sane.

Merging this, because it's great!

**Comment by ykempf** [comment]
Note that all this was run with testpackage, so it should be a bit cleaner imho. But I recently saw the largest diffs way upstream from the ionosphere so we have something with AMR going on.

**Pull request merged**
