### PR TITLE
Threadsafe randomgen: up to date with dev, slight changes to testpackage 

### PR DESCRIPTION
**Pull request by markusbattarbee**
In preparation for GPU merging: threadsafe randomgen, which is used there. Removed the old deprecated vamr test. Changed it so that all testpackage tests have blockcounts of even numbers, so if running WID=8 we can halve it.

### CODE REVIEW

**Comment by markusbattarbee** [comment]
So I also decided to incorporate already here what's brewing for GPUs as well; getting rid of spatial and velocity space sampling at init. If one sample per v-space cell is not enough, then neither is the v-space resolution in general. :)

**Comment by markusbattarbee** [comment]
Hmm, don't merge yet, `Flowthrough_trans_periodic` crashes...

**Comment by markusbattarbee** [comment]
Don't quite know what was wrong with the previous commit (it worked on 2 other platforms) but this new one works on lumi-c too. So good to go.

**Comment by markusbattarbee** [comment]
Ok, I was able to pinpoint the diffs against GPU that I was seeing to the Multipeak initialization algorithm. Now this should be good to go.

**Comment by ursg** [comment]
Alright then!

**Pull request merged**
